name: movies_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.17.0'
  flutter: '>=2.10.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  freezed_annotation: ^2.0.3
  go_router:
  hooks_riverpod:
  http:
  meta:
  simple_logger:
  url_launcher: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: 2.0.3
  build_runner:
  go_router_builder:
  json_serializable:
  mockito:
  pedantic_mono:
flutter:
  uses-material-design: true
  assets:
    - .env
